spring.application.name=SmartExpense

spring.data.mongodb.uri= mongodb+srv://arghaghosh276_db_user:Argha%409330@cluster0.cv09bkz.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=SmartExpenceDb
spring.data.mongodb.auto-index-creation=true
